# Generated by Django 5.1.4 on 2025-02-27 03:16

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tag',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
