# Generated by Django 5.1.4 on 2025-02-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='tier',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
