# Generated by Django 5.1.4 on 2025-02-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_benefit_tier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Benefit',
        ),
    ]
